# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:         
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Test maven installation'
        # Default value if no value is explicitly provided
        default: 'Maven & Java'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Github events
      run: echo "Hello ${{ github.event.inputs.name }}"
    - name: JAVA 8 And MAVEN Action
      # You may pin to the exact commit or the version.
      # uses: kobi-lemberg/github-maven-step@7f20340a98fc9890b1e47260368175df671788b1
      uses: kobi-lemberg/github-maven-step@java8_new
      with:
        # Command to run
        command: echo "JAVA_HOME- $JAVA_HOME M2_HOME- $M2_HOME MAVEN_HOME- $MAVEN_HOME"
        
        
        
